dist: xenial
language: c

cache:
  directories:
    - $HOME/gcc-arm-none-eabi-8-2018-q4-major
    - $HOME/nrf_sdk/15.3.0

env:
  global:
    - GNU_INSTALL_ROOT="$HOME/gcc-arm-none-eabi-8-2018-q4-major/bin/"
    - NORDIC_SDK_PATH="$HOME/nrf_sdk/15.3.0"
    - PATH="$PATH:$HOME/gcc-arm-none-eabi-8-2018-q4-major/bin"

  matrix:
    - BOARD=particle_xenon # Release
    - BOARD=particle_xenon DEBUG=1 # DEBUG

before_install:
  - chmod +x $TRAVIS_BUILD_DIR/.travis/before_install.sh

install:
  - $TRAVIS_BUILD_DIR/.travis/before_install.sh
  # Verify the arm-none-eabi-gcc binary is working correctly
  - arm-none-eabi-gcc --version

script:
  - make
